ifneq ($(CONFIG_USB_QTI_KS_BRIDGE),)
     KBUILD_CPPFLAGS += -DCONFIG_USB_QTI_KS_BRIDGE
endif

ifneq ($(CONFIG_PCIE_EMULATION),)
     KBUILD_CPPFLAGS += -DCONFIG_PCIE_EMULATION
endif

ifneq ($(CONFIG_USB_EMULATION),)
     KBUILD_CPPFLAGS += -DCONFIG_USB_EMULATION
endif

ifneq ($(CONFIG_IPC_ROUTER),)
     KBUILD_CPPFLAGS += -DCONFIG_IPC_ROUTER
endif

ifneq ($(CONFIG_CNSS2_PCIE),)
     KBUILD_CPPFLAGS += -DCONFIG_CNSS2_PCIE
endif

ifneq ($(CONFIG_CNSS2_USB),)
     KBUILD_CPPFLAGS += -DCONFIG_CNSS2_USB
endif

ifneq ($(CONFIG_DIAG_IPC_BRIDGE),)
     KBUILD_CPPFLAGS += -DCONFIG_DIAG_IPC_BRIDGE
endif

ifneq ($(CONFIG_DIAG_MHI),)
     KBUILD_CPPFLAGS += -DCONFIG_DIAG_MHI
endif

ifneq ($(CONFIG_DIAG_HSIC),)
     KBUILD_CPPFLAGS += -DCONFIG_DIAG_HSIC
endif

ifneq ($(CONFIG_MHI_XPRT),)
     KBUILD_CPPFLAGS += -DCONFIG_MHI_XPRT
endif

ifneq ($(CONFIG_HSIC_XPRT),)
     KBUILD_CPPFLAGS += -DCONFIG_HSIC_XPRT
endif

ifneq ($(CONFIG_IPC_ROUTER_SECURITY),)
     KBUILD_CPPFLAGS += -DCONFIG_IPC_ROUTER_SECURITY
endif

ifneq ($(CONFIG_MSM_MHI),)
     KBUILD_CPPFLAGS += -DCONFIG_MSM_MHI
endif

ifneq ($(CONFIG_MSM_QMI_INTERFACE),)
     KBUILD_CPPFLAGS += -DCONFIG_MSM_QMI_INTERFACE
endif

ifneq ($(CONFIG_MSM_DIAG_INTERFACE),)
     KBUILD_CPPFLAGS += -DCONFIG_MSM_QMI_INTERFACE
endif

ifneq ($(CONFIG_CNSS2),)
     KBUILD_CPPFLAGS += -DCONFIG_CNSS2
endif

ifneq ($(CONFIG_CNSS2_DEBUG),)
     KBUILD_CPPFLAGS += -DCONFIG_CNSS2_DEBUG
endif

ifneq ($(CONFIG_QMI_ENCDEC),)
     KBUILD_CPPFLAGS += -DCONFIG_QMI_ENCDEC
endif

ifneq ($(CONFIG_QMI_ENCDEC_DEBUG),)
     KBUILD_CPPFLAGS += -DCONFIG_QMI_ENCDEC_DEBUG
endif

ifneq ($(CONFIG_NAPIER_X86),)
     KBUILD_CPPFLAGS += -DCONFIG_NAPIER_X86
endif

CDEFINES :=	-Wall\
		-Werror
KBUILD_CPPFLAGS += $(CDEFINES)

obj-$(CONFIG_USB_QTI_KS_BRIDGE) += ks_bridge/
obj-$(CONFIG_MSM_MHI) += mhi/
obj-$(CONFIG_IPC_ROUTER) += ipc_router/
obj-$(CONFIG_MHI_XPRT) += xprt/
obj-$(CONFIG_HSIC_XPRT) += hsic_xprt/
obj-$(CONFIG_MSM_QMI_INTERFACE) += qmi/
obj-$(CONFIG_MSM_DIAG_INTERFACE) += diag/
obj-$(CONFIG_CNSS2) += cnss2/
obj-$(CONFIG_DIAG_IPC_BRIDGE) += diag_ipc_bridge/
